name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
    
env:
  TZ: Asia/Shanghai
  IP2L_DL: download.pl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Builder
        uses: actions/checkout@v3
        with:
          path: build
          ref: build
      - name: Checkout Data
        uses: actions/checkout@v3
        with:
          path: data
          ref: master
      - name: Parse
        run: |
          cd build
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./data        
          set qqwry_up = 0
          if [ -z "$(git status --porcelain)" ]; then
            echo "No qqwry changes to the output on this push"
          else
            echo "$(date '+%Y%m%d%H%M%S')" > ./data/qqwry.ver
            qqwry_up = 1
          fi
          
          cd ..
          mkdir -p ip2l
          chmod +x $IP2L_DL
          ./$IP2L_DL -package DB1 -token ${{ secrets.IP2LOCATION }} -output ./ip2l/c.zip
          ./$IP2L_DL -package DB1IPV6 -token ${{ secrets.IP2LOCATION }} -output ./ip2l/c6.zip
          cd ./ip2l
          unzip -o c.zip
          unzip -o c6.zip
          zip -q ip2l.zip *.CSV
          cp *.CSV ../data/ip2location/
          cp ip2l.zip ../data/ip2location/

          set ip2l_up = 0
          if [ -z "$(git status --porcelain)" ]; then
            echo "No ip2l changes to the output on this push"
          else
            echo "$(date '+%Y%m%d%H%M%S')" > ../data/ip2l.ver
            ip2l_up = 1
          fi
          
          if [ $qqwry_up = 1 ] || [ $ip2l_up = 1 ]; then
            cd ../data
            git config --global user.name "github-actions[bot]"
            git config --global user.email "bw@bw.com"
            git add .
            git commit -m "[auto] $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
