name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
    
env:
  TZ: Asia/Shanghai
  IP2L_DL: download.pl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Builder
        uses: actions/checkout@v3
        with:
          path: build
          ref: build
      - name: Checkout Data
        uses: actions/checkout@v3
        with:
          path: data
          ref: master
      - name: Parse
        run: |
          cd build
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo -E apt-get -qq install libwww-perl
          sudo -E apt-get -qq install libcrypt-ssleay-perl

          cd ./data        
          echo $PWD
          set qqwry_up = 0
          if [ -z "$(git status --porcelain)" ]; then
            echo "No qqwry changes to the output on this push"
          else
            echo "$(date '+%Y%m%d%H%M%S')" > ./data/qqwry.ver
            qqwry_up = 1
          fi
          
          cd ..
          mkdir -p ip2l
          echo $PWD
          
          ls ./data
