name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
    
env:
  TZ: Asia/Shanghai
  IP2L_DL: download.pl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Builder
        uses: actions/checkout@v3
        with:
          path: build
          ref: build
      - name: Checkout Data
        uses: actions/checkout@v3
        with:
          path: data
          ref: master
      - name: Parse
        run: |
          ll
          cd build
      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ll
          cd ./data
          ll

          
